CREATE SEQUENCE SEQ_USUARIO INCREMENT 1 START 1;
CREATE SEQUENCE SEQ_TOKEN INCREMENT 1 START 1;
CREATE SEQUENCE SEQ_PAIS INCREMENT 1 START 1;

CREATE TABLE usuario (
	id				INT				PRIMARY KEY ,
	login 			VARCHAR(100) 	UNIQUE,
	senha			VARCHAR(100),
	nome			VARCHAR(100),
	administrador	BOOLEAN	
);

CREATE TABLE token (
	id				INT				PRIMARY KEY ,
	token			VARCHAR(10000),
	login			VARCHAR(100),
	expiracao		TIMESTAMP,
	administrador	BOOLEAN
);
CREATE TABLE PAIS (
	id				INT				PRIMARY KEY ,
	nome			VARCHAR(100),
	sigla			VARCHAR(100),
	gentilico		VARCHAR(100)
);